Add .bat Files for Windows Use
wuningxi/Timetrack pull request #1
Opened 2020-11-03 12:32 UTC by Tom271

To be able use timetrack on Windows, I've created some quick .bat files to replace the .sh file for Unix systems and added a section to the README. This is my first time writing batch scripts so there will definitely be some improvements to be made! Just in case they are useful for others. I also had to remove the `src.` from the `from src.single_calendar ..., from src.plotting ... , from src.helpers ..` lines in `multi_calendar.py` and `single_calendar.py`. I've left that off this pull request as I can't test if the same change is necessary on Mac.

Thanks for creating a great tool!

2020-11-03 23:21 UTC, wuningxi requested changes
Thanks for porting the project to Windows, Tom! It looks good. I've added some comments for moving the Windows instructions in `README.md` and changing back to the previous working directory after executing the python scripts as this might be more convenient for users. Regarding the removal of `src.`, you can add this to the pull request as well, as it will still work on Mac.

2020-11-03 23:21 UTC, wuningxi commented on timetrack_single_cal.bat
> +SET %TIMETRACKDIR=\Users\nicole\code\timetrack
Add `SET PREVDIR=%CD%` here to save the previous working directory

2020-11-03 23:21 UTC, wuningxi commented on timetrack_single_cal.bat
> +CALL python src\single_calendar.py %*
add `CALL cd %PREVDIR%` to go back to the previous working directory

2020-11-03 23:21 UTC, wuningxi commented on timetrack_multi_cal.bat
> +ECHO %CD%
The print statement is no longer necessary if we switch back to the previous working directory

2020-11-03 23:21 UTC, wuningxi commented on timetrack_multi_cal.bat
> +SET %TIMETRACKDIR=\Users\nicole\code\timetrack
Add `SET PREVDIR=%CD%` here to save the previous working directory

2020-11-03 23:21 UTC, wuningxi commented on timetrack_single_cal.bat
> +ECHO %CD%
The print statement is no longer necessary if we switch back to the previous working directory

2020-11-03 23:21 UTC, wuningxi commented on timetrack_multi_cal.bat
> +CALL python src\multi_calendar.py %*
add CALL cd %PREVDIR% to go back to the previous working directory

2020-11-03 23:21 UTC, wuningxi commented on README.md
> +Note that these functions will *not* return you to the directory you began in but will move you to the timetrack folder.
The last line can be deleted with proposed changes.

2020-11-03 23:21 UTC, wuningxi commented on README.md
> +- Add the timetrack folder to the system path environment variables. This allows the use of `timetrack_multi_cal` and `timetrack_single_cal` from anywhere in the command line. On Windows 10, this is
Thanks for adding these instructions regarding the Windows setup. Could you move them further up to `## Setup` (maybe under a separate `### Windows` section), so they're easier to find?

2020-11-04 10:28 UTC, Tom271 commented
Thanks for the review, I've made all the changes you suggested and updated the PR.

2020-11-04 18:24 UTC, wuningxi approved these changes
Thanks for the changes 👍

2020-11-04 18:26 UTC, merged

2020-11-04 18:27 UTC, wuningxi commented
I'm pulling the changes into the `windows-support` branch just to make sure everything is working fine before merging with the main branch.